# Generated by Django 2.1.5 on 2019-01-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('p_ganados', models.PositiveSmallIntegerField(default=0)),
                ('p_empatados', models.PositiveSmallIntegerField(default=0)),
                ('p_perdidos', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('goles', models.PositiveSmallIntegerField(default=0)),
                ('t_amarillas', models.PositiveSmallIntegerField(default=0)),
                ('t_rojas', models.PositiveSmallIntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futsal.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('NJ', 'No Jugado'), ('EV', 'En Vivo'), ('TE', 'Terminado')], default='NJ', max_length=2)),
                ('equipo1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Equipo1', to='futsal.Equipo')),
                ('equipo2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Equipo2', to='futsal.Equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futsal.Grupo'),
        ),
    ]
