# Generated by Django 2.1.5 on 2019-01-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='resultado1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
